USE data_analysis_project;
SELECT * FROM customer_churn LIMIT 10;

-- Business Insights Questions

-- Which category generates highest revenue?

SELECT  category, ROUND(SUM(purchased_amount),2) AS highest_revenue
FROM customer_churn GROUP BY category
ORDER BY highest_revenue DESC;

-- Are discounts actually increasing purchase value?

SELECT discount_applied, ROUND(SUM(purchased_amount),2) AS total_revenue, 
ROUND(AVG(purchased_amount),2) AS avg_purchase
FROM customer_churn GROUP BY discount_applied;

-- What is the total revenue generated by male and female customer ? 
SELECT gender, ROUND(SUM(purchased_amount),2) AS highest_revenue
FROM customer_churn GROUP BY gender ORDER BY highest_revenue DESC;

-- Which customer used a discount but still spent more then the average purchase amount ?
SELECT customer_id, purchased_amount, discount_applied
FROM customer_churn WHERE discount_applied= 'Yes' AND 
purchased_amount > (SELECT AVG(purchased_amount) FROM customer_churn) LIMIT 10;

-- Which are the top/bottom 5 products with the highest average review rating. 
SELECT item_purchased, ROUND(AVG(review_rating),2) AS Avg_ratings
FROM customer_churn GROUP BY item_purchased
ORDER BY Avg_ratings DESC LIMIT 5;

SELECT item_purchased, ROUND(AVG(review_rating),2) AS Avg_ratings
FROM customer_churn GROUP BY item_purchased
ORDER BY Avg_ratings ASC LIMIT 5;

-- Average purchase: Standard vs Express shipping
SELECT shipping_type, COUNT(DISTINCT customer_id) as order_placed,
ROUND(AVG(purchased_amount),2)  as avg_purchase, ROUND(SUM(purchased_amount),2) AS revenue
FROM customer_churn GROUP BY shipping_type ORDER BY revenue DESC;

-- Do subscribed customers spend more ? Compare average speed and total revenue between subscribers and non-subscribers.
SELECT subscription_status,	COUNT(customer_id) as users, ROUND(AVG(purchased_amount),2) as avg_revenue,
ROUND(SUM(purchased_amount),2) as total_revenue
FROM customer_churn GROUP BY subscription_status ORDER BY total_revenue DESC;

-- Top 5 products with highest discount usage %

SELECT item_purchased, COUNT(item_purchased) AS total_number_of_times_sold,
COUNT(CASE WHEN discount_applied='Yes' THEN 1 END) AS  Number_of_times_sold_when_disocunt_applied,
COUNT(CASE WHEN discount_applied='Yes' THEN 1 END) *100.0 / COUNT(*) AS discount_percent
FROM customer_churn GROUP BY item_purchased ORDER BY discount_percent DESC LIMIT 5;

-- Segment customer into new, returning and loyal based on their total number of previous purchase, and show the count of each segment.
SELECT 
	CASE 
		WHEN previous_purchases= '0' THEN 'New Customer'
		WHEN previous_purchases BETWEEN 1 AND 15  THEN 'Returning Customer'
	ELSE 'Loyal Customers'
END AS customer_segment,
COUNT(*) AS customer_count FROM customer_churn
GROUP BY CASE 
		WHEN previous_purchases= '0' THEN 'New Customer'
		WHEN previous_purchases BETWEEN 1 AND 15  THEN 'Returning Customer'
	ELSE 'Loyal Customers'
END;

-- What are the top 3 most purchased products within each category ?
SELECT
	CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
	END AS customer_type, subscription_status, COUNT(*) AS customer_count,
	COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY CASE 
											WHEN previous_purchases > 5 THEN 'Repeat Buyers'
										ELSE 'Normal Buyers'
									END
									) AS percents FROM customer_churn
GROUP BY CASE 
		WHEN previous_purchases > 5 THEN 'Repeat Buyers'
		ELSE 'Normal Buyers'
	END,subscription_status;
    
-- What is the revenue contribution of each age group ? 
SELECT 
	CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN Age BETWEEN 26 AND 35 THEN '26-35'
		WHEN Age BETWEEN 36 AND 50 THEN '35-50'
		ELSE '51+'
	END AS age_group, ROUND(SUM(purchased_amount),2) AS total_revenue
FROM customer_churn
GROUP BY CASE 
		WHEN age BETWEEN 18 AND 25 THEN '18-25'
		WHEN Age BETWEEN 26 AND 35 THEN '26-35'
		WHEN Age BETWEEN 36 AND 50 THEN '35-50'
		ELSE '51+'
	END
	ORDER BY total_revenue DESC;



